version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: epc-resto-db
    ports:
      - 54321:5432
    volumes:
      - epc_resto_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=epc-resto
  redis:
    image: bitnami/redis:latest
    container_name: epc-resto-redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  app:
    entrypoint: ['nest', 'start', '--debug', '0.0.0.0:9229', '--watch']
    container_name: epc-resto-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  epc_resto_db_data:
    name: db_data
